### ISSUE TITLE
Installation challenges

### ISSUE THREAD

**Issue by stevenbedrick** [plandes/mimicsid#2]
Hello! I am attempting to install mimicsid via pip, and have run into assorted and sundry problems. My setup has been to create brand-new virtualenvs, without anything else installed; I've tried both Python 3.10 and 3.11. 

Under Python 3.10, I was able to eventually get Pip to install the `zensols.mimicsid` package if I included `--use-pep517` alongside the `--use-deprecated=legacy-resolver` argument, but it gave a warning about how I would end up with the wrong version of Pydantic installed, and sure enough, actually trying to run anything using mimicsid resulted in a lengthy set of errors involving Pydantic type imports happening very deep within the system. I tried manually installing the version of Pydantic that mimicsid seems to want (something less than 2.0, so 1.10.13), and that got me past the Pydantic-related errors, but then ran into the problem that `zensols.dbpg` was not installed. Manually installing that actually resulted in code that could run, but it appears to hang indefinitely after finishing downloading and extracting various embedding models. I tried increasing the log level to DEBUG, which at least gave me a lot of logging output and then resulted in the program crashing- something about hitting a recursion limit in a config parser. So clearly, whatever I did to get things installed did not actually result in a working installation! 😆 

At this point, I gave up on 3.10, and tried installing things in Python 3.11, thinking perhaps that was my issue. That also seemed to need the `--use-pep517` argument; it at least was able to figure out what it needed to build, but when building it ran into the problem that something, somewhere, was telling pip to install a version of nmslib that (judging from the compilation error messages) is not compatible with Python 3.11.

I have attached logs for the problems with both Python 3.10 and Python 3.11. Any advice, help, heroic rescues, etc. would be most welcome! Thank you!
[python_3.10.txt](https://github.com/plandes/mimicsid/files/13957762/python_3.10.txt)
[python_3.11..txt](https://github.com/plandes/mimicsid/files/13957764/python_3.11.txt)

**Comment by plandes** [comment]
@stevenbedrick Hi, sorry you're having so many problem.  This package has a lot of dependencies--both in terms of libraries and models.

The Python 3.10 previous versions of the `mimicsid` used an earlier version of spaCy that required the legacy dependency manager, and is fraught with issues because of that.  The `dbpg` package is used to get MIMIC-III notes from a PostgreSQL database, but if all you want is to use the model for inferencing it should not need that package. If it does let me know and I'll fix that in the latest version\.

The `nmslib` library isn't related to this package.  Unfortunately I had this issue in both macOS and Linux, which resulted in a need to clone that repo and build from source.

I recommend sticking with the latest, which includes Python 3.11 and:

1. Create a new environment just for `mimicsid` (virtual with `python -m venv`, conda, or whatever)
2. `pip install wheel`
3. Clone the [nmslib repo](https://github.com/nmslib/nmslib).
4. `cd nmslib`
5. `python setup.py bdist_wheel`.

Now you have the nmslib package for other environments. Of course you need to install it in the `mimicsid` project.

Finally the `pip install mimicsid` should work.

Let me know how this goes.

**Comment by stevenbedrick** [comment]
Thank you so much for the detailed and helpful reply! I was able to manually build the nmslib wheel, and after installing it, I was then able to successfully run `pip install zensols.mimicsid`. Trying to run my script, however, ran into the same problem I encountered earlier- it does seem like something somewhere _is_ depending on `zensols.dbpg`, as I got an error about that module being missing. In my particular case, I just want to use the pre-trained models to do inference on new inputs, so don't actually need the (very useful-sounding!) package to pull things from an already-loaded MIMIC database- but there's no harm from my perspective in having the package installed, either.

Anyway, I manually installed `zensols.dbpg` from pip, and that got me a step further. However, I am now running into a _new_ error when I try and call `ApplicationFactory.section_predictor()`; it's a kind of long stack trace (att.), but the proximate error seems to be this:

> `zensols.config.configbase.ConfigurableError: No section: 'medcat_status_move_update' in file /Users/bedricks/PycharmProjects/mimicSectionScratch/.venvs/lib/python3.11/site-packages/zensols/mimicsid/resources/app.conf`

Any suggestions would be most welcome!

PS- if I run my script with logging enabled, even at the INFO level, it dies long before this point with that weird recursion error that I mentioned, so besides a rogue unmanaged `dbpg` dependency, there might also be something lurking in there about how logging is happening. But that's presumably a different problem from what I am running into...

[with_manual_nmslib.txt](https://github.com/plandes/mimicsid/files/13967835/with_manual_nmslib.txt)

**Comment by plandes** [comment]
It was a configuration conflict with a previously trained (section ID) model.  Please reinstall with:

`pip install -U zensols.mimicsid`

Then retry and let me know.

Note the (new) [warning](https://github.com/plandes/mimicsid#medcat-models) regarding the MedCAT models.  If I recall, I do not believe the section ID models use CUI features, so I don't think this will affect you.

**Comment by stevenbedrick** [comment]
That did the trick, thank you! Works like a champ. :-)

**Comment by plandes** [comment]
@stevenbedrick Thanks finding and reporting this issue.  These things can be frustrating, but this package has so many moving parts.
